### ISSUE TITLE
Add relative ETA change to copy estimates

### ISSUE THREAD

**Issue by morgo** [cashapp/spirit#137]
It is expected that inserting into a larger table can slow down. This is particularly true if the table has unique indexes or is using Aurora (can't use insert buffer).

It is difficult for the copier to project the rate of which the slow down is occuring, but I wonder if (for multi-day DDLs) it is easier to surface it. i.e.

```
copier-remaining-time=217h7m22s (+30h from 1d ago).
```

This makes it very clear that as long as the estimate is going up by a lot, the value itself can't be trusted that much.

**Comment by jayjanssen** [comment]
sanity check design goals:
* output shows at most 1 day ago, older estimates can be discarded
* output will show at minimum 1 hour ago, or nothing if there is no data
* as the day progresses, the output will show the oldest output stored (i.e., `from 1h ago`, `from 2h ago`, etc.)
* Once a full day is reached, the lookback history is a sliding window
* Lookback history is stored in hourly increments only, so only 24 records at most.
