### ISSUE TITLE
Use Docker instead of dbdeployer for local testing

### ISSUE THREAD

**Issue by daniel-nichter** [cashapp/spirit#187]
I propose we use Docker rather than dbdeployer because Docker is industry standard, and I bet it's far more common with developers than dbdeployer. It's also pretty easy to set up multiple version with Docker Compose.

If you agree, I'll do a PR later.

**Comment by morgo** [comment]
Since this issue was created, dbdeployer has reached end of life. I'm adding the help-wanted tag to this issue.
