### ISSUE TITLE
Confirm in README.md minimum grants required for spirit to work

### ISSUE THREAD

**Issue by sjmudd** [cashapp/spirit#219]
Thanks for sharing this new tool. It looks interesting.
It would be useful to share **the minimum grants required by spirit** both on the primary/master and also on the replica.
You provide 2 different dsnd so grants for each one could be different as the read access probably requires less privileges.
So a short section on: **Grants required by spirit** would avoid us trying to figure that out and also _avoid us_ unnecessarily granting `ALL PRIVILEGES` to the user(s) when auditors and other paranoid people might want access reduced to as little as necessary.

**Comment by morgo** [comment]
Thank you for the feature request. It is a reasonable expectation to have this documented, I will begin working on it shortly.
