### ISSUE TITLE
Does it support connecting to pull binlog from the replica?

### ISSUE THREAD

**Issue by ht2324** [cashapp/spirit#223]
When I tested, I found that I could only set the host of the primary node to connect.

**Comment by ht2324** [comment]
If I configure the ip of the replica node, then ddl will only be executed from the replica node
and gh-ost supports configuring replica IP

**Comment by morgo** [comment]
Replicas are only supported for throttling.

Spirit also works a little bit different to gh-ost, in that gh-ost will read the table on a replica to determine the start and end position for chunks. If the primary key is an auto_increment, Spirit will just generate these ranges optimistically by itself. For non-auto-inc keys, it uses the gh-ost approach, but reads from the primary node. [Docs are here](https://github.com/cashapp/spirit/blob/main/pkg/table/README.md).

**Comment by ht2324** [comment]
If reading from the primary node, will it cause greater pressure on the online environment?

**Comment by morgo** [comment]
Possibly, but not necessarily:
- Writes are often the bottleneck.
- The read is well optimized. If the pages are not in the buffer pool, it can also have a pre-warming effect for the chunk copy which will follow.
- Binlog subscribing is usually low cost. There are some edge-cases such as with a very high trivial insert rate it could cause pressure on the network stack having to send N packets to M subscribers but this is not that common. Spirit at certain points needs to use the primary's binlog to ensure it has all the changes (before checksum, before cutover).

**Comment by ht2324** [comment]
> Possibly, but not necessarily:
> 
> * Writes are often the bottleneck.
> * The read is well optimized. If the pages are not in the buffer pool, it can also have a pre-warming effect for the chunk copy which will follow.
> * Binlog subscribing is usually low cost. There are some edge-cases such as with a very high trivial insert rate it could cause pressure on the network stack having to send N packets to M subscribers but this is not that common. Spirit at certain points needs to use the primary's binlog to ensure it has all the changes (before checksum, before cutover).

Got it, thanks for the answer

**Comment by morgo** [comment]
No problem, closing this issue!
