### ISSUE TITLE
Delay cutover feature

### ISSUE THREAD

**Issue by morgo** [cashapp/spirit#244]
I would like to propose that we add a new feature to 'delay cutover'. This is currently supported by gh-ost, but not by Spirit.

For the implementation I propose that:
- We create an additional table called the "cutover signal" (or something like that; TBD)
- When copy and checksum phases have finished, spirit blocks waiting for the cutover signal to be dropped.
- As soon as it is no longer present, the cutover phase is initiated.

The idea being that this will allow users to schedule their cutover (which requires an MDL lock) to an opportune time. Technically the checksum also requires an MDL lock, so we may need further discussion on that, but this is the basic idea.

**Comment by kolbe** [comment]
I am working on this in https://github.com/kolbe/spirit/tree/defer-cutover

I'm using the term "deferred cutover", as "delay" to me sounds like it would have a specific time associated with it.

I chose to call the signal table a "sentinel".

The current behavior is to check every 1 second for 48 hours and then exit with an error if the sentinel table has not been dropped. If spirit is then restarted, it should resume from checkpoint and quickly start waiting again for the sentinel to be dropped.

The primary missing piece of functionality right now is in handling a situation where spirit is killed or times out waiting for the sentinel table to be deleted, following which an operator might remove the sentinel table before running spirit again. At present, spirit will re-create the sentinel table (assuming the `--defer-cutover` flag is used again) and block again waiting for it to be deleted.
