### ISSUE TITLE
Support for MariaDB

### ISSUE THREAD

**Issue by bobzilladev** [cashapp/spirit#252]
I've been able to get spirit to work on a `10.5.23` MariaDB system, this is an issue to house the pull request demonstrating the changes I had to make. Unknown if MariaDB would be a goal of yours, but pt-osc is too slow for the size of some of our tables. Caveat that we haven't gone through large production alters with this change yet.

**Comment by morgo** [comment]
Thank you for the feature request.

Unfortunately, support for MariaDB is not planned. Please see our [philosophy on feature requests here](https://github.com/cashapp/spirit/blob/main/.github/CONTRIBUTING.md#philosophy).

**Comment by bobzilladev** [comment]
Ah, very well, will close these out.
