### ISSUE TITLE
Why not design it as a web version?

### ISSUE THREAD

**Issue by jeffaryhe** [cashapp/spirit#265]
Why not design it as a web version that supports the selection of databases and tables and the modification or addition of corresponding fields. It is best to manually perform cut switching on the web.

**Comment by morgo** [comment]
It is possible to add this layer of automation on top of spirit. We have something similar where our internal tooling effectively embeds Spirit.

We do not have any immediate plans to offer a GUI directly as a top-level feature.

**Comment by morgo** [comment]
I'm going to close this for now. Thanks for the question!
