### ISSUE TITLE
Partitioning fails due to SQL syntax error

### ISSUE THREAD

**Issue by DevMasterSoonToBe** [cashapp/spirit#277]
Hi, 

I have an issue when trying to partition table with below command:
**_./spirit \
--host=${DB_HOST} \
--username=${DB_USERNAME} \
--password=${DB_PASSWORD} \
--database=xxxx \
--table=xxxxx \
--alter="PARTITION BY KEY() PARTITIONS 8" \
--defer-cutover=true \
--checksum=true \
--skip-drop-after-cutover=true \_**

the output I get is:
_**INFO[0000] Starting spirit migration: concurrency=4 target-chunk-size=500ms table=xxxxx.xxxxxx alter="PARTITION BY KEY() PARTITIONS 8"
INFO[0000] unable to use INPLACE: ALTER either does not support INPLACE or when performed as INPLACE could take considerable time. Use --force-inplace to override this safety check
INFO[0000] could not resume from checkpoint: reason=could not read from table '_xxxxxx_chkpnt'
spirit: error: Error 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ', ALGORITHM=COPY**_

The same command worked in gh-ost, does it have to do something with how spirit works?

**Comment by morgo** [comment]
The `ALGORITHM=COPY` is added to when the new table is created to prevent burning an `INSTANT` version.

This looks like it might be a regression of https://github.com/cashapp/spirit/pull/272 , I will take a look.

**Comment by morgo** [comment]
I can reproduce. It looks like algorithm assertions are not supported for every DDL:

```
mysql> alter table stock PARTITION BY KEY() PARTITIONS 8;
Query OK, 1000000 rows affected (4.82 sec)
Records: 1000000  Duplicates: 0  Warnings: 0

mysql> alter table stock PARTITION BY KEY() PARTITIONS 8, algorithm=copy;
ERROR 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ', algorithm=copy' at line 1
mysql> alter table stock PARTITION BY KEY() PARTITIONS 8 algorithm=copy;
ERROR 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'algorithm=copy' at line 1
```

This is news to me, but we can work around it.

**Comment by DevMasterSoonToBe** [comment]
Should I build from master and try again?

**Comment by morgo** [comment]
Yes please. We don't offer binaries, but this is fixed in main.
