### ISSUE TITLE
go-mysql version being used panics on long passwords

### ISSUE THREAD

**Issue by T0MM0R** [cashapp/spirit#361]
Bug is fixed in v1.9.0 of [go-mysql](https://github.com/go-mysql-org/go-mysql/commit/5c82c1f91206c9cf4535acfafef88353dacaa2f4)
If password is greater than 19 characters canal panics with `Failed to register slave; too long 'report-password'`

**Comment by morgo** [comment]
Thank you for reporting this. We will fix it soon!
